// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ProfilePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"py-12 sm:py-16 lg:py-20\"><div class=\"max-w-lg mx-auto px-4 sm:px-6\"><!-- Loading state --><div id=\"profile-loading\" class=\"text-center py-12\"><p class=\"text-neutral-500 dark:text-neutral-400\">Loading profile...</p></div><!-- Not authenticated --><div id=\"profile-unauthenticated\" class=\"hidden text-center py-12\"><p class=\"text-neutral-500 dark:text-neutral-400 mb-4\">You are not logged in.</p><a href=\"/login\" class=\"inline-block px-6 py-3 bg-neutral-900 dark:bg-neutral-100 text-white dark:text-neutral-900 font-medium rounded-xl hover:bg-neutral-700 dark:hover:bg-neutral-200 transition-colors\">Log In</a></div><!-- Profile content --><div id=\"profile-content\" class=\"hidden\"><h1 class=\"text-3xl font-bold text-neutral-900 dark:text-neutral-100 mb-8\">Profile</h1><div class=\"bg-white dark:bg-neutral-800 border border-neutral-200 dark:border-neutral-700 rounded-2xl p-6 space-y-5\"><div><p class=\"text-sm font-medium text-neutral-500 dark:text-neutral-400\">Email</p><p id=\"profile-email\" class=\"text-lg text-neutral-900 dark:text-neutral-100 mt-1\"></p></div><div><p class=\"text-sm font-medium text-neutral-500 dark:text-neutral-400\">Roles</p><div id=\"profile-roles\" class=\"flex flex-wrap gap-2 mt-1\"></div></div><div><p class=\"text-sm font-medium text-neutral-500 dark:text-neutral-400\">User ID</p><p id=\"profile-id\" class=\"text-sm text-neutral-600 dark:text-neutral-300 mt-1 font-mono\"></p></div></div><button onclick=\"logout()\" class=\"mt-6 w-full py-3 bg-red-600 text-white font-medium rounded-xl hover:bg-red-700 transition-colors\">Log Out</button></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
